### ISSUE TITLE
Queries don't work in vagrant without Remote Splits being set to true

### ISSUE THREAD

**Issue by fire** [kuenishi/presto-riak#12]
https://github.com/kuenishi/presto-riak/blob/master/src/main/java/com/basho/riak/presto/CoverageSplit.java#L110

What does this parameter do?

**Comment by kuenishi** [comment]
That prohibits remote access over distributed erlang, to guarantee locality. presto-riak used to have riak-java-client only access mode, but it's stale as I didn't have enough bandwidth to test them.
